### ISSUE TITLE
作者，您好！关于.list.yml该怎么设置？亦或者我该怎样解决下方的报错？

### ISSUE THREAD

**Issue by Chuc-Jie** [oGsLP/livestream-checker#1]
### 运行报错

```

|  livestream-checker (v0.1.0 20-03-13)
|  本程序由oGsLP提供, www.github.com/oGsLP/livestream-checker, 喜欢的话可以给个star >_<

Traceback (most recent call last):
  File ".../livestream-checker-master/main.py", line 22, in <module>
    start()
  File ".../livestream-checker-master/main.py", line 16, in start
    c.add_to_list("斗鱼", 6556593)
  File "...\livestream-checker-master\lib\checker.py", line 60, in add_to_list
    if room in self.__list[platform]:
TypeError: 'NoneType' object is not subscriptable

进程已结束,退出代码1
```

### 我运行【**main**】文件  后出现上方错误代码，我检查了一下【 **.list.yml** 】文件，里面是空的

**Comment by oGsLP** [comment]
应该是这样的格式
```yaml
斗鱼:
  - 100
  - 101
战旗:
  - 1000
  - 1001
```
平台及对应的房间号列表的yaml文件

项目很久之前的了，出现bug很正常，已经不能用了属于是，项目中爬取的直播平台有几个都已经没了>_>

**Comment by Chuc-Jie** [comment]
啊这样，好的，谢谢你的解惑！
